"""
Django settings.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    # Admin web UI at /admin.
    "django.contrib.admin",

    # Core authentication framework and its default models.
    "django.contrib.auth",
    
    # Django content type system (allows permissions to be associated with models).
    "django.contrib.contenttypes",

    # Session-based auth (cookies).
    "django.contrib.sessions",

    # django.contrib.messages is Django’s built-in framework for displaying one-time
    # notification messages (often called "flash messages"). It allows you to
    # temporarily store a message in a user's session during one request and
    # display it on the immediately subsequent request—such as a "Login successful"
    # or "Form submitted" notification.
    "django.contrib.messages",

    # Serves CSS/JS/images.
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    # HTTPS redirects, security headers.
    "django.middleware.security.SecurityMiddleware",

    # Manages sessions across requests.
    "django.contrib.sessions.middleware.SessionMiddleware",

    # URL normalization (trailing slashes).
    "django.middleware.common.CommonMiddleware",

    # CSRF protection for forms.
    "django.middleware.csrf.CsrfViewMiddleware",

    # Associates users with requests using sessions.
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # Flash messages.
    "django.contrib.messages.middleware.MessageMiddleware",

    # Prevents clickjacking via iframes.
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# The URL prefix for static files in the browser (/static/style.css)
STATIC_URL = "static/"

# The local folder where collectstatic dumps everything for Web Server to serve
STATIC_ROOT = BASE_DIR / "staticfiles"
